# Generated by Django 4.2 on 2025-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=150)),
                ('publication_year', models.PositiveBigIntegerField()),
                ('sypnopsis', models.TextField()),
            ],
        ),
    ]
