# Generated by Django 4.2 on 2025-11-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sypnopsis',
            new_name='synopsis',
        ),
    ]
